### ISSUE TITLE
Recorder: Application crashes on I/O errors

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#21]
- When the targets file format is incorrect
- When the output directory can't be accessed

**Comment by Dirskin** [comment]
The first point was fixed in dae48a779ea6b5d6706e1944d0780457ca34ab47.
The second point (output directory error handling) suppose to be handled. when closing the folder selector the program doesn't crash. How to reproduce?

**Comment by drordotan** [comment]
To reproduce point 2 -
1. Start a session
2. Rename/delete the output directory (this simulates an I/O error)
3. Write something on the tablet
