### ISSUE TITLE
Encoder: the expected trials.csv format is too strict

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#44]
Encoder checks the precise list of columns in trials.csv. There's no need for that. You only need to make sure that the required columns are there.

**Comment by drordotan** [comment]
Other comments with respect to this:
- I am not sure I understand why you examine two possible formats instead of one. Is it because of optional columns?
- Write more details in exceptions. Which fields are missing?
- The list of CSV column names (or mandatory columns) should be written only in one place in the code, not duplicated in several locations.

**Comment by rl100** [comment]
> Other comments with respect to this:
> 
> * I am not sure I understand why you examine two possible formats instead of one. Is it because of optional columns?
> * Write more details in exceptions. Which fields are missing?
> * The list of CSV column names (or mandatory columns) should be written only in one place in the code, not duplicated in several locations.

**Comment by rl100** [comment]
When the Encoder reads the Recorders output, it adds columns to trials.csv.
Thus, in order to be able to read both coded and uncoded trials.csv we have to examine these two possible formats - with the new columns, and without.
