### ISSUE TITLE
Recorder: trajectories are rotated

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#49]
![image](https://user-images.githubusercontent.com/20823892/85951644-231e8d00-b96d-11ea-9cd2-2e995591c6bf.png)

**Comment by drordotan** [comment]
In this specific trial, they are also rotated in plotter

**Comment by Dirskin** [comment]
Is it only in this specific trial? Are the other trials in the session rotated as well? 
is it the last version of the recorder? Similar issue was already fixed in #36

**Comment by mayachini** [comment]
כל המילים מוצגות בסיבוב. 
כשאני הופכת את הטבלט אז זה מופיע הפוך ברקורדר ותקין באנקודר

**Comment by Dirskin** [comment]
Fixed. The rotate button now sets the rotation angle and rotates the display.
When closing a trial, a rotation in a matching angle is applied to the trajectory file as a whole.
