### ISSUE TITLE
Encoder: automatic splitting to characters is incorrect

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#50]
There should be 6 characters here, encoder identified 4:

![image](https://user-images.githubusercontent.com/20823892/85951655-4b0df080-b96d-11ea-97eb-0ee479d663fc.png)

**Comment by rl100** [comment]
I wrote to you about it by Email. 
The dots splits to strokes by pressure value of 0. In these raw traj files there is no pressure = 0 between all of the strokes. I don't know what causes this problem, but it comes from the recording. 
We can set a new threshold value which is slightly bigger than 0 and it will fix the problem specifically, but not in general.
Do you know what can cause this error?

**Comment by rl100** [comment]
I changed pressure threshold value to 5 for now, seems working.
But still, we have to check why she is not getting the proper pressure = 0 where needed.
