### ISSUE TITLE
Recorder: restart session

### ISSUE THREAD

**Issue by mayachini** [drordotan/writracker#59]
אחרי הפסקת סשן בהפעלה מחדש האפליקציה נסגרת.
זה קורה רק בהפעלה מחדש של אותו סשן מבלי שיצאתי לגמרי מהתוכנה.

**Comment by Dirskin** [comment]
Fixed in 2125cc5343f17dc838d778b21691fdd4ae77c35f. 
I Actually think what was fixed was another issue that caused the same bug, but the problem does not happen again.
