### ISSUE TITLE
Encoder: window menu disappear

### ISSUE THREAD

**Issue by mayachini** [drordotan/writracker#61]
בכמה מקרים למרות שרואים את כל החלון במסך לא מופיע התפריט התחתון בכלל. 
זה לא אותו דבר כמו במקרה שהחלון גדול מידי כי פה רואים את כל החלון אבל בכל זאת אין תפריט

![רקורדר](https://user-images.githubusercontent.com/67582862/86401641-44f07a80-bcb3-11ea-8cc8-3ff6ec07f6e5.png)

**Comment by drordotan** [comment]
This is a copy of issue #60
