### ISSUE TITLE
Encoder: on top of the "enter response" window, write how many characters exist in the response

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#65]

**Comment by rl100** [comment]
What to you mean by "how many characters exist in the response"?

**Comment by drordotan** [comment]
E.g. that the participant wrote 8 characters, i.e. I must type an
8-character response too


On 31 July 2020 at 18:48:26, rl100 (notifications@github.com) wrote:

What to you mean by "how many characters exist in the response"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/drordotan/writracker/issues/65#issuecomment-667191663>,
or unsubscribe

**Comment by rl100** [comment]
It is already written if you press the OK button before entering a response.
The response can include a different number of characters from the participant number of characters

**Comment by drordotan** [comment]
Indeed you present this info when opening the response screen from "accept" - this is excellent. 

But I would like to see this info also when I just click "enter response", and this popup opens:
![image](https://user-images.githubusercontent.com/20823892/89117399-22b26e00-d4a6-11ea-83c2-c79528de6147.png)

True, in this situation we don't necessarily expect the same number of characters, so maybe just add a line saying "the participant wrote ## characters".

**Comment by rl100** [comment]
Fixed.
