### ISSUE TITLE
Encoder: ask user to confirm before performing critical commands

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#73]
Add a "please confirm" popup, with ok/cancel buttons, before performing the following:
- Reset trial
- Quit
- Skip trial (explain that this trial will not be saved to the encoded-data folder) - if possible, have a possible response "OK and don't ask again". If not possible, this should be the default - otherwise it will be hard to click SKIP several times.

**Comment by rl100** [comment]
Added to Quit, Reset and Delete for now.
