### ISSUE TITLE
Encoder: change stroke colors

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#79]
For standard strokes, use two colors alternately, like now: shades of cyan (same as now), and shades of orange (instead of red).
Self-correction strokes: same colors, but with a red contour to each dot (if the red doesn't look good, try yellow).

**Comment by rl100** [comment]
Done. 
For self correction strokes, I colored the stroke dots in red and yellow alternatively (any preferred colors?..). Its more distinguishable.
